version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/.."
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "integration"
    # Labels on pull requests for version updates only
    labels:
      - "pip dependencies"
