version: '3'
services:
  jupiter:
    env_file:
      - .env
    container_name: 'cdapython-notebook'
    image: jupyter/minimal-notebook:2023-05-29
    working_dir: /home/joyvan/work
    ports:
      - '${NOTEBOOK_PORT}:8888'
    volumes:
      - ./notebooks:/home/joyvan/work

    command: >
      sh -c "
      pip install git+https://github.com/CancerDataAggregator/cda-python.git@${GIT_TAG_VERSION_CDA_PYTHON} --no-cache-dir
      && /usr/local/bin/start.sh jupyter notebook --NotebookApp.token=''
      "
