version: '3'
services:
  jupiter:
    env_file:
      - .env
    container_name: 'cdapython-notebook'
    image: us-central1-docker.pkg.dev/broad-cda-dev/cda-docker-images/cdapython-notebook-3.11:latest
      
    working_dir: /home/joyvan/work
    ports:
      - '${NOTEBOOK_PORT}:8888'
    volumes:
      - ./notebooks:/home/joyvan/work
    command: "/usr/local/bin/start.sh jupyter notebook --NotebookApp.token=''"