[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]

[tool.mypy]
ignore_missing_imports = true
plugins = "numpy.typing.mypy_plugin"
strict = false
warn_return_any = true
follow_imports = "silent"


[tool.black]
line-length = 88
target-version = ['py37']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
