start:function+ 

function: FUNCTION_NAME "(" function_arg  ")"


function_arg: [value ("," (" ")* function_arg)*] 


value: quoted_identifier | "*" |  SIGNED_NUMBER | WORD



quoted_identifier: "'" [WORD] "'"

FUNCTION_NAME: LETTER+


%import common._STRING_ESC_INNER
%import common.ESCAPED_STRING
%import common.DIGIT
%import common.SIGNED_NUMBER
%import common.FLOAT
%import common.LETTER
%import common.WORD
%import common.WS
%import common.NEWLINE
%ignore WS

