from unittest import mock

from cdapython import Q
from cdapython.results.result import Result
from tests.fake_result import FakeResultData

# from tests.global_settings import host, table
result = [
    {
        "id": "01BR020",
        "identifier": [
            {"system": "GDC", "value": "01BR020"},
            {"system": "PDC", "value": "01BR020"},
            {"system": "IDC", "value": "01BR020"},
        ],
        "species": "homo sapiens",
        "sex": "not reported",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["CPTAC-2", "cptac_brca"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": "Not Reported",
    },
    {
        "id": "01CO022",
        "identifier": [
            {"system": "GDC", "value": "01CO022"},
            {"system": "PDC", "value": "01CO022"},
            {"system": "IDC", "value": "01CO022"},
        ],
        "species": "homo sapiens",
        "sex": "female",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["CPTAC-2", "cptac_coad"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "11CO042",
        "identifier": [
            {"system": "GDC", "value": "11CO042"},
            {"system": "PDC", "value": "11CO042"},
            {"system": "IDC", "value": "11CO042"},
        ],
        "species": "homo sapiens",
        "sex": "male",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["CPTAC-2", "cptac_coad"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "11CO057",
        "identifier": [
            {"system": "GDC", "value": "11CO057"},
            {"system": "PDC", "value": "11CO057"},
            {"system": "IDC", "value": "11CO057"},
        ],
        "species": "homo sapiens",
        "sex": "male",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["CPTAC-2", "cptac_coad"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "1833",
        "identifier": [{"system": "GDC", "value": "1833"}],
        "species": "homo sapiens",
        "sex": "not reported",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["OHSU-CNL"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "2201",
        "identifier": [{"system": "GDC", "value": "2201"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "white",
        "ethnicity": "Unknown",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Alive",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "2307",
        "identifier": [{"system": "GDC", "value": "2307"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "white",
        "ethnicity": "Unknown",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Dead",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "2314",
        "identifier": [{"system": "GDC", "value": "2314"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Alive",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "2390",
        "identifier": [{"system": "GDC", "value": "2390"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "white",
        "ethnicity": "hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Dead",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "2431",
        "identifier": [{"system": "GDC", "value": "2431"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Dead",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "28",
        "identifier": [
            {"system": "GDC", "value": "28"},
            {"system": "PDC", "value": "28"},
        ],
        "species": "homo sapiens",
        "sex": "male",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": [
            "Human Early-Onset Gastric Cancer - Korea University",
            "ORGANOID-PANCREATIC",
            "Integrated Proteogenomic Characterization of HBV-related Hepatocellular carcinoma",
        ],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "4156",
        "identifier": [{"system": "GDC", "value": "4156"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["OHSU-CNL"],
        "vital_status": "Dead",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "4495",
        "identifier": [{"system": "GDC", "value": "4495"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["OHSU-CNL"],
        "vital_status": "Unknown",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10074",
        "identifier": [{"system": "GDC", "value": "AD10074"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10114",
        "identifier": [{"system": "GDC", "value": "AD10114"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10200",
        "identifier": [{"system": "GDC", "value": "AD10200"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10292",
        "identifier": [{"system": "GDC", "value": "AD10292"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10443",
        "identifier": [{"system": "GDC", "value": "AD10443"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10521",
        "identifier": [{"system": "GDC", "value": "AD10521"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10665",
        "identifier": [{"system": "GDC", "value": "AD10665"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10723",
        "identifier": [{"system": "GDC", "value": "AD10723"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10788",
        "identifier": [{"system": "GDC", "value": "AD10788"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10796",
        "identifier": [{"system": "GDC", "value": "AD10796"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10801",
        "identifier": [{"system": "GDC", "value": "AD10801"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD10826",
        "identifier": [{"system": "GDC", "value": "AD10826"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11105",
        "identifier": [{"system": "GDC", "value": "AD11105"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11210",
        "identifier": [{"system": "GDC", "value": "AD11210"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11225",
        "identifier": [{"system": "GDC", "value": "AD11225"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11236",
        "identifier": [{"system": "GDC", "value": "AD11236"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11333",
        "identifier": [{"system": "GDC", "value": "AD11333"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11348",
        "identifier": [{"system": "GDC", "value": "AD11348"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11392",
        "identifier": [{"system": "GDC", "value": "AD11392"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11393",
        "identifier": [{"system": "GDC", "value": "AD11393"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11456",
        "identifier": [{"system": "GDC", "value": "AD11456"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11466",
        "identifier": [{"system": "GDC", "value": "AD11466"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11762",
        "identifier": [{"system": "GDC", "value": "AD11762"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11815",
        "identifier": [{"system": "GDC", "value": "AD11815"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD11870",
        "identifier": [{"system": "GDC", "value": "AD11870"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12078",
        "identifier": [{"system": "GDC", "value": "AD12078"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12184",
        "identifier": [{"system": "GDC", "value": "AD12184"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12213",
        "identifier": [{"system": "GDC", "value": "AD12213"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12334",
        "identifier": [{"system": "GDC", "value": "AD12334"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12362",
        "identifier": [{"system": "GDC", "value": "AD12362"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12379",
        "identifier": [{"system": "GDC", "value": "AD12379"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12511",
        "identifier": [{"system": "GDC", "value": "AD12511"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12546",
        "identifier": [{"system": "GDC", "value": "AD12546"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12597",
        "identifier": [{"system": "GDC", "value": "AD12597"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12690",
        "identifier": [{"system": "GDC", "value": "AD12690"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12695",
        "identifier": [{"system": "GDC", "value": "AD12695"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12752",
        "identifier": [{"system": "GDC", "value": "AD12752"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD12870",
        "identifier": [{"system": "GDC", "value": "AD12870"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13009",
        "identifier": [{"system": "GDC", "value": "AD13009"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13072",
        "identifier": [{"system": "GDC", "value": "AD13072"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13144",
        "identifier": [{"system": "GDC", "value": "AD13144"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD1323",
        "identifier": [{"system": "GDC", "value": "AD1323"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13284",
        "identifier": [{"system": "GDC", "value": "AD13284"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13364",
        "identifier": [{"system": "GDC", "value": "AD13364"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13432",
        "identifier": [{"system": "GDC", "value": "AD13432"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13612",
        "identifier": [{"system": "GDC", "value": "AD13612"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13832",
        "identifier": [{"system": "GDC", "value": "AD13832"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD13844",
        "identifier": [{"system": "GDC", "value": "AD13844"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD1409",
        "identifier": [{"system": "GDC", "value": "AD1409"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14132",
        "identifier": [{"system": "GDC", "value": "AD14132"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14218",
        "identifier": [{"system": "GDC", "value": "AD14218"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14297",
        "identifier": [{"system": "GDC", "value": "AD14297"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14348",
        "identifier": [{"system": "GDC", "value": "AD14348"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14355",
        "identifier": [{"system": "GDC", "value": "AD14355"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14540",
        "identifier": [{"system": "GDC", "value": "AD14540"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14681",
        "identifier": [{"system": "GDC", "value": "AD14681"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14826",
        "identifier": [{"system": "GDC", "value": "AD14826"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD14908",
        "identifier": [{"system": "GDC", "value": "AD14908"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15106",
        "identifier": [{"system": "GDC", "value": "AD15106"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15178",
        "identifier": [{"system": "GDC", "value": "AD15178"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15235",
        "identifier": [{"system": "GDC", "value": "AD15235"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15271",
        "identifier": [{"system": "GDC", "value": "AD15271"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15307",
        "identifier": [{"system": "GDC", "value": "AD15307"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15313",
        "identifier": [{"system": "GDC", "value": "AD15313"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD1558",
        "identifier": [{"system": "GDC", "value": "AD1558"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15618",
        "identifier": [{"system": "GDC", "value": "AD15618"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15667",
        "identifier": [{"system": "GDC", "value": "AD15667"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15713",
        "identifier": [{"system": "GDC", "value": "AD15713"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15751",
        "identifier": [{"system": "GDC", "value": "AD15751"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD1580",
        "identifier": [{"system": "GDC", "value": "AD1580"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD15958",
        "identifier": [{"system": "GDC", "value": "AD15958"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD1597",
        "identifier": [{"system": "GDC", "value": "AD1597"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16167",
        "identifier": [{"system": "GDC", "value": "AD16167"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16175",
        "identifier": [{"system": "GDC", "value": "AD16175"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16291",
        "identifier": [{"system": "GDC", "value": "AD16291"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD1633",
        "identifier": [{"system": "GDC", "value": "AD1633"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16443",
        "identifier": [{"system": "GDC", "value": "AD16443"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16447",
        "identifier": [{"system": "GDC", "value": "AD16447"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16470",
        "identifier": [{"system": "GDC", "value": "AD16470"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD1658",
        "identifier": [{"system": "GDC", "value": "AD1658"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16708",
        "identifier": [{"system": "GDC", "value": "AD16708"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16766",
        "identifier": [{"system": "GDC", "value": "AD16766"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16780",
        "identifier": [{"system": "GDC", "value": "AD16780"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16791",
        "identifier": [{"system": "GDC", "value": "AD16791"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD16964",
        "identifier": [{"system": "GDC", "value": "AD16964"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD17050",
        "identifier": [{"system": "GDC", "value": "AD17050"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "id": "AD17166",
        "identifier": [{"system": "GDC", "value": "AD17166"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
]

fake = FakeResultData(result)
results: Result = Result(
    api_response=fake.api_response,
    offset=fake.offset,
    limit=fake.limit,
    api_instance=fake.api_instance,
    show_sql=fake.show_sql,
    show_count=fake.show_count,
    format_type=fake.format_type,
)


@mock.patch("cdapython.Q.run", return_value=results)
def test_is(a) -> None:
    d = Q("dbgap_accession_number IS NOT null")
    print(type(d.to_json()))
    data = d.run().to_list()
    assert isinstance(data, list)


test_is()
