from unittest import mock

from cdapython import Q
from cdapython.results.result import Result
from tests.fake_result import FakeResultData
from tests.global_settings import integration_host, integration_table

result = [
    {
        "subject_id": "01OV008",
        "subject_identifier": [
            {"system": "GDC", "value": "01OV008"},
            {"system": "PDC", "value": "01OV008"},
            {"system": "IDC", "value": "01OV008"},
        ],
        "species": "homo sapiens",
        "sex": "female",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["cptac_ov", "CPTAC-2"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": "Not Reported",
    },
    {
        "subject_id": "04OV051",
        "subject_identifier": [
            {"system": "GDC", "value": "04OV051"},
            {"system": "PDC", "value": "04OV051"},
        ],
        "species": "homo sapiens",
        "sex": "female",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["CPTAC-2"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": "Not Reported",
    },
    {
        "subject_id": "11BR050",
        "subject_identifier": [
            {"system": "GDC", "value": "11BR050"},
            {"system": "PDC", "value": "11BR050"},
            {"system": "IDC", "value": "11BR050"},
        ],
        "species": "homo sapiens",
        "sex": "female",
        "race": "asian",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["cptac_brca", "CPTAC-2"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": "Not Reported",
    },
    {
        "subject_id": "11CO027",
        "subject_identifier": [
            {"system": "GDC", "value": "11CO027"},
            {"system": "PDC", "value": "11CO027"},
            {"system": "IDC", "value": "11CO027"},
        ],
        "species": "homo sapiens",
        "sex": "female",
        "race": "asian",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["CPTAC-2", "cptac_coad"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "11CO070",
        "subject_identifier": [
            {"system": "GDC", "value": "11CO070"},
            {"system": "PDC", "value": "11CO070"},
            {"system": "IDC", "value": "11CO070"},
        ],
        "species": "homo sapiens",
        "sex": "male",
        "race": "asian",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["CPTAC-2", "cptac_coad"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "124",
        "subject_identifier": [{"system": "PDC", "value": "124"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "chinese",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": [
            "Integrated Proteogenomic Characterization of HBV-related Hepatocellular carcinoma"
        ],
        "vital_status": "Alive",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "2056",
        "subject_identifier": [{"system": "GDC", "value": "2056"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "Unknown",
        "ethnicity": "Unknown",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Unknown",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "2164",
        "subject_identifier": [{"system": "GDC", "value": "2164"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Dead",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "2179",
        "subject_identifier": [{"system": "GDC", "value": "2179"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Dead",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "2261",
        "subject_identifier": [{"system": "GDC", "value": "2261"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "Unknown",
        "ethnicity": "Unknown",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Dead",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "2344",
        "subject_identifier": [{"system": "GDC", "value": "2344"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Alive",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "2492",
        "subject_identifier": [{"system": "GDC", "value": "2492"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Unknown",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "2563",
        "subject_identifier": [{"system": "GDC", "value": "2563"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "Unknown",
        "ethnicity": "Unknown",
        "days_to_birth": None,
        "subject_associated_project": ["BEATAML1.0-COHORT"],
        "vital_status": "Alive",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "61",
        "subject_identifier": [
            {"system": "GDC", "value": "61"},
            {"system": "PDC", "value": "61"},
        ],
        "species": "homo sapiens",
        "sex": "male",
        "race": "white",
        "ethnicity": "not hispanic or latino",
        "days_to_birth": None,
        "subject_associated_project": [
            "Integrated Proteogenomic Characterization of HBV-related Hepatocellular carcinoma",
            "ORGANOID-PANCREATIC",
            "Human Early-Onset Gastric Cancer - Korea University",
        ],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10096",
        "subject_identifier": [{"system": "GDC", "value": "AD10096"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10151",
        "subject_identifier": [{"system": "GDC", "value": "AD10151"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10167",
        "subject_identifier": [{"system": "GDC", "value": "AD10167"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10463",
        "subject_identifier": [{"system": "GDC", "value": "AD10463"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10528",
        "subject_identifier": [{"system": "GDC", "value": "AD10528"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10721",
        "subject_identifier": [{"system": "GDC", "value": "AD10721"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10764",
        "subject_identifier": [{"system": "GDC", "value": "AD10764"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10785",
        "subject_identifier": [{"system": "GDC", "value": "AD10785"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10790",
        "subject_identifier": [{"system": "GDC", "value": "AD10790"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD108",
        "subject_identifier": [{"system": "GDC", "value": "AD108"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10841",
        "subject_identifier": [{"system": "GDC", "value": "AD10841"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10879",
        "subject_identifier": [{"system": "GDC", "value": "AD10879"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD10952",
        "subject_identifier": [{"system": "GDC", "value": "AD10952"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11408",
        "subject_identifier": [{"system": "GDC", "value": "AD11408"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11551",
        "subject_identifier": [{"system": "GDC", "value": "AD11551"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11600",
        "subject_identifier": [{"system": "GDC", "value": "AD11600"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11624",
        "subject_identifier": [{"system": "GDC", "value": "AD11624"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11633",
        "subject_identifier": [{"system": "GDC", "value": "AD11633"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11752",
        "subject_identifier": [{"system": "GDC", "value": "AD11752"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11827",
        "subject_identifier": [{"system": "GDC", "value": "AD11827"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11902",
        "subject_identifier": [{"system": "GDC", "value": "AD11902"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11958",
        "subject_identifier": [{"system": "GDC", "value": "AD11958"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD11989",
        "subject_identifier": [{"system": "GDC", "value": "AD11989"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12003",
        "subject_identifier": [{"system": "GDC", "value": "AD12003"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12006",
        "subject_identifier": [{"system": "GDC", "value": "AD12006"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12043",
        "subject_identifier": [{"system": "GDC", "value": "AD12043"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12240",
        "subject_identifier": [{"system": "GDC", "value": "AD12240"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12260",
        "subject_identifier": [{"system": "GDC", "value": "AD12260"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12263",
        "subject_identifier": [{"system": "GDC", "value": "AD12263"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12311",
        "subject_identifier": [{"system": "GDC", "value": "AD12311"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12490",
        "subject_identifier": [{"system": "GDC", "value": "AD12490"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12494",
        "subject_identifier": [{"system": "GDC", "value": "AD12494"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD1255",
        "subject_identifier": [{"system": "GDC", "value": "AD1255"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12587",
        "subject_identifier": [{"system": "GDC", "value": "AD12587"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12830",
        "subject_identifier": [{"system": "GDC", "value": "AD12830"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD12883",
        "subject_identifier": [{"system": "GDC", "value": "AD12883"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13137",
        "subject_identifier": [{"system": "GDC", "value": "AD13137"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13319",
        "subject_identifier": [{"system": "GDC", "value": "AD13319"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13343",
        "subject_identifier": [{"system": "GDC", "value": "AD13343"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13369",
        "subject_identifier": [{"system": "GDC", "value": "AD13369"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13376",
        "subject_identifier": [{"system": "GDC", "value": "AD13376"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13453",
        "subject_identifier": [{"system": "GDC", "value": "AD13453"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13550",
        "subject_identifier": [{"system": "GDC", "value": "AD13550"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13569",
        "subject_identifier": [{"system": "GDC", "value": "AD13569"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13585",
        "subject_identifier": [{"system": "GDC", "value": "AD13585"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13638",
        "subject_identifier": [{"system": "GDC", "value": "AD13638"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD13811",
        "subject_identifier": [{"system": "GDC", "value": "AD13811"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD14015",
        "subject_identifier": [{"system": "GDC", "value": "AD14015"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD14199",
        "subject_identifier": [{"system": "GDC", "value": "AD14199"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD14350",
        "subject_identifier": [{"system": "GDC", "value": "AD14350"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD1443",
        "subject_identifier": [{"system": "GDC", "value": "AD1443"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD14460",
        "subject_identifier": [{"system": "GDC", "value": "AD14460"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD14462",
        "subject_identifier": [{"system": "GDC", "value": "AD14462"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD14507",
        "subject_identifier": [{"system": "GDC", "value": "AD14507"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD14545",
        "subject_identifier": [{"system": "GDC", "value": "AD14545"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15035",
        "subject_identifier": [{"system": "GDC", "value": "AD15035"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15052",
        "subject_identifier": [{"system": "GDC", "value": "AD15052"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15107",
        "subject_identifier": [{"system": "GDC", "value": "AD15107"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15220",
        "subject_identifier": [{"system": "GDC", "value": "AD15220"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15333",
        "subject_identifier": [{"system": "GDC", "value": "AD15333"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15344",
        "subject_identifier": [{"system": "GDC", "value": "AD15344"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15481",
        "subject_identifier": [{"system": "GDC", "value": "AD15481"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15493",
        "subject_identifier": [{"system": "GDC", "value": "AD15493"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15496",
        "subject_identifier": [{"system": "GDC", "value": "AD15496"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15600",
        "subject_identifier": [{"system": "GDC", "value": "AD15600"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15629",
        "subject_identifier": [{"system": "GDC", "value": "AD15629"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15681",
        "subject_identifier": [{"system": "GDC", "value": "AD15681"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15695",
        "subject_identifier": [{"system": "GDC", "value": "AD15695"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15739",
        "subject_identifier": [{"system": "GDC", "value": "AD15739"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD1583",
        "subject_identifier": [{"system": "GDC", "value": "AD1583"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15907",
        "subject_identifier": [{"system": "GDC", "value": "AD15907"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15920",
        "subject_identifier": [{"system": "GDC", "value": "AD15920"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD15975",
        "subject_identifier": [{"system": "GDC", "value": "AD15975"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD16010",
        "subject_identifier": [{"system": "GDC", "value": "AD16010"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD16031",
        "subject_identifier": [{"system": "GDC", "value": "AD16031"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD16233",
        "subject_identifier": [{"system": "GDC", "value": "AD16233"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD16346",
        "subject_identifier": [{"system": "GDC", "value": "AD16346"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD1647",
        "subject_identifier": [{"system": "GDC", "value": "AD1647"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD16613",
        "subject_identifier": [{"system": "GDC", "value": "AD16613"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD16713",
        "subject_identifier": [{"system": "GDC", "value": "AD16713"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD16740",
        "subject_identifier": [{"system": "GDC", "value": "AD16740"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD17007",
        "subject_identifier": [{"system": "GDC", "value": "AD17007"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD17156",
        "subject_identifier": [{"system": "GDC", "value": "AD17156"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD17175",
        "subject_identifier": [{"system": "GDC", "value": "AD17175"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD1730",
        "subject_identifier": [{"system": "GDC", "value": "AD1730"}],
        "species": "homo sapiens",
        "sex": "male",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
    {
        "subject_id": "AD17380",
        "subject_identifier": [{"system": "GDC", "value": "AD17380"}],
        "species": "homo sapiens",
        "sex": "female",
        "race": "not reported",
        "ethnicity": "not reported",
        "days_to_birth": None,
        "subject_associated_project": ["FM-AD"],
        "vital_status": "Not Reported",
        "days_to_death": None,
        "cause_of_death": None,
    },
]
fake = FakeResultData(result)
fake_result = Result(
    api_response=fake.api_response,
    query_id=fake.query_id,
    offset=fake.offset,
    limit=fake.limit,
    api_instance=fake.api_instance,
    show_sql=fake.show_sql,
    show_count=fake.show_count,
    format_type=fake.format_type,
)


@mock.patch("cdapython.Q.run", return_value=fake_result)
def test_age_at_death(_) -> None:
    q2 = Q(
        'vital_status IS null OR age_at_death = 0 AND sex = "male" OR sex = "female" '
    ).to_dataframe()


test_age_at_death()
