name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions/checkout@v2
      - name: Install formatter dependencies
        run: pip install black
      - name: Run Black check
        run: black --check .
